<html>
<body>
<link rel = "stylesheet"  type="text/css" href="index.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	
 	</div>
		<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %}
				<p style="font-size: 200%; border-bottom:none;">
				 Welcome {{ username | capitalize }} <BR>
				 You have <i id="basketQuantity">{{ num_items | raw }}</i> items in your basket<BR>

				                                {% if num_items > 0 %}
                                <a href='shoppingBagPage.php'>View Basket</a> or
                                <a href='paymentDetailsPage.php'>Checkout</a><BR>
                                {% endif %}

				<a href='logout.php'>Log Out</a></p>
					{% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span style="color:#20B2AA" class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
					<span style="color:#20B2AA" class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUserPage.php">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

<div id="content">

<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="search_Menu.php?department=All%20Clothes&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Women%27s%20Clothes&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Mens%27s%20Clothes&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Dress&depart=womenswear&type=dress">Dress</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Skirt&depart=womenswear&type=skirt">Skirt</a></li>
				</ul>
            </li>
            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Shorts&depart=menswear&type=shorts">Shorts</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Kilt&depart=menswear&type=kilt">Kilt</a></li>
				<hr>
				<li><a href="search_Menu.php?department=T-Shirts&depart=menswear&type=tShirts">T-Shirts</a></li>
				</ul>
            </li>
            <li>
            <a href="storeLocatorPage.php">STORE LOCATOR</a>
            </li>
            <li>
            <a href="aboutUsPage.php">ABOUT US</a>
            </li>
	</ul>
</div>

<div id="middle" style="margin-top:50px; font-size:132%; font-weight:bold;width:60%;line-height:175%;">	
This website was developed as a group project for Web Application Development at University of Strathclyde.<BR>
Team members were James Byrne, Larissa Leite, Tiago de França Queiroz, Sara Torabi, Elen Wall.<BR>
The store is entirely fictional so please do not try to order anything from us unless you do so for just testing and
certainly do not enter your real personal details and credit card unless you would like us to go on a spending spree
with your credit card.<img style="margin-left:5px;  height:20px;"  src= "wink.jpg" >
</div>

<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>
</body>
</html>