<html>
<head>
<meta charset="UTF-8">

<script type='text/javascript' language='Javascript'>
<!--

var images = Array();

var i = 0;

{% for id in styleID %}
	images[{{ id.id }}] = new Image();
	images[{{ id.id }}].src = "{{ id.thumbnail_link }}";
{% endfor %}


function changeImage()
{
	var e = document.getElementById("style_ID");
	var strUser = e.options[e.selectedIndex].value;
	document['imgStyle'].src = images[strUser].src;
}

//-->
</script>
</head>
<body>
<a id="tooCool" href="http://www.w3junkies.com/toocool/">Too Cool for Internet Explorer</a>
<link rel = "stylesheet"  type="text/css" href="addUser.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	</div>
 	<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %} Welcome {{ username | capitalize }} <BR> <a
					href='logout.php'>Log Out</a> {% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
						<span class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					<br> <br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUser.html">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

	<div id="content">

		<div id="nav">
			<ul>
				<li><a href="admin.php">ADMIN MENU</a></li>
				<li><a href="addStylePage.php">ADD STYLE</a></li>
				<li><a href="addItemPage.php">ADD ITEM</a></li>
			</ul>

		</div>

		<div id="AddItemForm">
			<fieldset>

				<h1 style="text-align: center;">Add Item Form</h1>
				<br> <br>
				<form method="POST" action="addItem.php">
					<table style="white-space: nowrap;">
						<tr valign="top">
							<td><strong>Style ID</strong></td>
							{% for id in styleID %}
								{% if loop.first %}
									<img id="imgStyle" src="{{ id.thumbnail_link }}" width="144" high="216" style="float: right;" /><td>
									<select name="style_ID" id="style_ID" onchange="changeImage();">
								{% endif %}
								<option value="{{ id.id }}">{{ id.name }}</option>
								{% if loop.last %}
									</select></td>
								{% endif %}
							{% endfor %}
						</tr>

						<tr valign="top">
							<td><strong>Colour</strong></td>
							<td><select name="colour">
									<option value="blue">Blue</option>
									<option value="black">Black</option>
									<option value="red">Red</option>
									<option value="white">White</option>
									<option value="yellow">Yellow</option>
									<option value="pink">Pink</option>
									<option value="gray">Gray</option>
									<option value="green">Green</option>
							</select></td>
						</tr>

						<tr valign="top">
							<td><strong>Size</strong></td>
							<td><select name="item_size">
									<option value="xsamall">X-Small</option>
									<option value="small">Small</option>
									<option value="medium">Medium</option>
									<option value="large">Large</option>
									<option value="xlarge">X-Large</option>
									<option value="xxlarge">XX-Large</option>
									<option value="xxxlarge">XXX-Large</option>
							</select></td>
						</tr>

						<tr valign="top">
							<td><strong>Price</strong></td>
							<td><input type="text" name="price" size="25"></td>
						</tr>

						<tr valign="top">
							<td><strong>Stock</strong></td>
							<td><input type="text" name="stock" size="25"></td>
						</tr>

						<tr valign="top">
							<td><strong>Image Link</strong></td>
							<td><input type="text" name="image_link" size="25"></td>
						</tr>

						<tr valign="top">
							<td><input type="submit" value="Submit"
								style="margin-top: 20px; background: -webkit-gradient(linear, left top, left 25, from(#FFFFFF), color-stop(4%, #EEEEEE), to(#E0EEEE) );" />
							</td>

							<td><input type="reset" value="Clear"
								style="margin-top: 20px; background: -webkit-gradient(linear, left top, left 25, from(#FFFFFF), color-stop(4%, #EEEEEE), to(#E0EEEE) );" />
							</td>
						</tr>

					</table>
				</form>
				{% if success is defined %}
					{% if success == 1 %}
						Item added!
					{% else %}
						Error, try again!
					{% endif %}
				{% endif %}
			</fieldset>
		</div>
	</div>



	<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
