<html>
<head>
<meta charset="UTF-8">
</head>
<body>
<a id="tooCool" href="http://www.w3junkies.com/toocool/">Too Cool for Internet Explorer</a>
<link rel = "stylesheet"  type="text/css" href="addUser.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	</div>
 	<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %} Welcome {{ username | capitalize }} <BR> <a
					href='logout.php'>Log Out</a> {% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
						<span class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUser.html">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

	<div id="content">

		<div id="nav">
			<ul>
				<li><a href="admin.php">ADMIN MENU</a></li>
				<li><a href="addStylePage.php">ADD STYLE</a></li>
				<li><a href="addItemPage.php">ADD ITEM</a></li>
			</ul>

		</div>
		<div id="AddItemForm">
			<fieldset>
				<h1 style="text-align: center;">Add Syle Form</h1>
				<br> <br>
				<form id="addStylefrm" method="POST" action="addStyle.php">
					<table style="white-space: nowrap;">
						<tr valign="top">
							<td><strong>Name:</strong></td>
							<td><input type="text" name="name"></td>
						</tr>

						<tr valign="top">
							<td><strong>Department:</strong></td>
							<td><select name="department">
									<option value="womenswear">Womenswear</option>
									<option value="menswear">Menswear</option>
							</select></td>
						</tr>

						<tr valign="top">
							<td><strong>Type:</strong></td>
							<td><select name="type">
									<option value="coats">Coats & Jackets</option>
									<option value="Jeans">Jeans</option>
									<option value="knitwear">Knitwear</option>
							</select></td>
						</tr>

						<tr valign="top">
							<td><strong>Material:</strong></td>
							<td><input type="text" name="material"></td>
						</tr>

						<tr valign="top">
							<td><strong>Thumbnail Link:</strong></td>
							<td><input type="text" name="thumbnail"></td>
						</tr>

						<tr valign="top">
							<td><strong>Description:</strong></td>
							<td><textarea rows="10" cols="20" name="description"></textarea>
							</td>
						</tr>

						<tr valign="top">
							<td><input type="submit" value="Submit" /></td>
							<td><input type="reset" value="Clear" /></td>
						</tr>
					</table>

				</form>
				{% if success is defined %}
					{% if success == 1 %}
						{{ name | raw }} added!
					{% else %}
						Error, try again!
					{% endif %}
				{% endif %}
		
		</div>
		</fieldset>
	</div>

	<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
