<html>
<head>
<meta charset="UTF-8">
	<script type='text/javascript' language='Javascript'>

<!--
var requestObject = false;

		function funcReceiveData() {
			if (requestObject.readyState == 4) {
				if (requestObject.status == 200) {
					var status = requestObject.responseText;
					if (status == "ok") {
						document.getElementById('userValid').innerHTML = 'Valid e-mail';
					} else if (status == "emailError") {
						document.getElementById('userValid').innerHTML = 'Invalid e-mail, please choose another one';
					} else {
						document.getElementById('userValid').innerHTML = ' Email already registred, please choose another one.';
					}
				}
			}
		}

		if (window.XMLHttpRequest) {
			requestObject = new XMLHttpRequest();
		} else if (window.ActiveXObject) {
			requestObject = new ActiveXObject("Microsoft.XMLHTTP");
		}

		function checkUser() {
			if (requestObject) {
				requestObject.open("POST", "checkusername.php", true);
				requestObject.setRequestHeader("Content-type",
						"application/x-www-form-urlencoded");
				var user = document.getElementById('email').value;
				var tobesent = "email=" + user;
				requestObject.send(tobesent);
				requestObject.onreadystatechange = funcReceiveData;
			}
		}
	//-->
	</script>
</head>
<body>


<link rel = "stylesheet"  type="text/css" href="addUser.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	
 	</div>
		<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %}
				<p style="font-size: 200%; border-bottom:none;">
				 Welcome {{ username | capitalize }} <BR>
				 You have <i id="basketQuantity">{{ num_items | raw }}</i> items in your basket<BR>
				<a href='shoppingBagPage.php'>View Basket</a> or 
				<a href='paymentDetailsPage.php'>Checkout</a><BR>
				<a href='logout.php'>Log Out</a></p>
					{% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
						<span class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUserPage.php">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

	<div id="content">
 
<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="search_Menu.php?department=All%20Cloths&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Woman%27s%20Cloths&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Mans%27s%20Cloths&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Dress&depart=womenswear&type=dress">Dress</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Skirt&depart=womenswear&type=skirt">Skirt</a></li>
				</ul>
            </li>
            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Shorts&depart=menswear&type=shorts">Shorts</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Kilt&depart=menswear&type=kilt">Kilt</a></li>
				<hr>
				<li><a href="search_Menu.php?department=T-Shirts&depart=menswear&type=tShirts">T-Shirts</a></li>
				</ul>
            </li>
            <li>
            <a href="#">STORE LOCATOR</a>
            </li>
            <li>
            <a href="#">ABOUT US</a>
            </li>
	</ul>
</div>

	<div id="signUpForm">
		<fieldset>

		<h1 style="text-align:center; ">Sign-up Form</h1>
		<br><br>
	<form method="POST" action="addUser.php">
		<table style="white-space: nowrap;">
			<tr valign="top">
				<td><strong>Email</strong><br>
				<input type="text" name="email" id="email" onblur="checkUser();" size="25"><br><i id='userValid'></i></td>
								<td><strong>Address line 2</strong><br>
				<input type="text" name="address2" size="35"></td>
			</tr>
			
			<tr valign="top">
				<td><strong>Password</strong><br>
				<input type="password" name="password" size="25"></td>
								<td><strong>City</strong><br>
				<input type="text" name="city" size="25"></td>
			</tr>

			<tr valign="top">
				<td><strong>First name</strong><br>
				<input type="text" name="Fname" size="25"></td>
								<td><strong>Postcode</strong><br>
				<input type="text" name="postcode" size="25"></td>
			</tr>

			<tr valign="top">
				<td><strong>Last name</strong><br>
				<input type="text" name="Lname" size="25"></td>
				<td><strong>Phone</strong><br>
				<input type="text" name="phone" size="25"></td>
			</tr>

			<tr valign="top">
				<td><strong>Address line 1</strong><br>
				<input type="text" name="address1" size="35"></td>
								<td><strong>Mobile</strong><br>
				<input type="text" name="mobile" size="25"></td>
			</tr>
			
			<tr>
				<td><input type="submit" value="Submit" style="margin-top:20px; background: -webkit-gradient(linear, left top, left 25, from(#FFFFFF), color-stop(4%, #EEEEEE), to(#E0EEEE));" /></td>
				<td><input type="reset" value="Clear" style="margin-top:20px; background: -webkit-gradient(linear, left top, left 25, from(#FFFFFF), color-stop(4%, #EEEEEE), to(#E0EEEE));"/></td>
			</tr>
		</table>
	</form>
	</fieldset>
	</div>

<div id="footer">
	<br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
