<html>
<head>
<meta charset="UTF-8">
	<script type='text/javascript' language='Javascript'>

<!--
var requestObject = false;

		function funcReceiveData()
		{
			if (requestObject.readyState == 4)
			{
				if (requestObject.status == 200)
				{
					var status = requestObject.responseText;
					alert(status);
				}
			}
		}

		if (window.XMLHttpRequest)
		{
			requestObject = new XMLHttpRequest();
		}
		else if (window.ActiveXObject)
		{
			requestObject = new ActiveXObject("Microsoft.XMLHTTP");
		}

		function addToBag()
		{
			if (requestObject) 
			{
				requestObject.open("POST", "addToBag.php", true);
				requestObject.setRequestHeader("Content-type",
						"application/x-www-form-urlencoded");
				var size = document.getElementById('selectSize').value;
				var colour = document.getElementById('selectColour').value;
				var tobesent = "size=" + size + "&" + "colour=" + colour + "&styleID={{ style_ID | raw }}&name={{ item.name | raw }}";
				requestObject.send(tobesent);
				requestObject.onreadystatechange = funcReceiveData;
			}
		}
	</script>
	
	<meta charset="UTF-8">

<script type='text/javascript' language='Javascript'>
<!--

var i = 0;
var j = 0;
var validColours = new Array();
var coloursArray = new Array();
	{% for key, vec in size_colour %}
		var {{ key }} = [
		         {% for colour in vec %}
               		{% if loop.last %}
               			"{{ colour }}"];
						validColours[i++] = "{{ key }}";
					{% else %}
						"{{ colour }}",
					{% endif %}
					{% if loop.last %}
						coloursArray[j++] = {{ key }};
					{% endif %}
				{% endfor %}
		{% endfor %}
		//alert(validColours.join('\n'));
		//alert(coloursArray.join('\n'));

		//--------------------------------------------------------------------------------------------
		i = 0;
		j = 0;
		var validSizes = new Array();
		var SizesArray = new Array();
			{% for key, vec in colour_size %}
				var {{ key }} = [
				         {% for size in vec %}
		               		{% if loop.last %}
		               			"{{ size }}"];
								validSizes[i++] = "{{ key }}";
							{% else %}
								"{{ size }}",
							{% endif %}
							{% if loop.last %}
								SizesArray[j++] = {{ key }};
							{% endif %}
						{% endfor %}
				{% endfor %}

				//alert(validSizes.join('\n'));
				//alert(SizesArray.join('\n'));
//-->

function colourChanged()
{
	var i = 0;
	var select_tag = document.getElementById('selectSize');
	select_tag.options.length=0;
	for(i = 0; i < SizesArray[0].length; i++)
	{
		select_tag.options[i]=new Option(SizesArray[0][i], SizesArray[0][i], false, false);
	}
}

function sizeChanged()
{
	var i = 0;
	var select_tag = document.getElementById('selectColour');
	select_tag.options.length=0;
	for(i = 0; i < coloursArray[0].length; i++)
	{
		select_tag.options[i]=new Option(coloursArray[0][i], coloursArray[0][i], false, false);
	}
}

function startAll()
{
	var i = 0;
	var select_tag = document.getElementById('selectColour');
	select_tag.options.length=0;
	for(i = 0; i < coloursArray[0].length; i++)
	{
		select_tag.options[i]=new Option(coloursArray[0][i], coloursArray[0][i], false, false);
	}

	var i = 0;
	var select_tag = document.getElementById('selectSize');
	select_tag.options.length=0;
	for(i = 0; i < SizesArray[0].length; i++)
	{
		select_tag.options[i]=new Option(SizesArray[0][i], SizesArray[0][i], false, false);
	}
}
window.onload = startAll;
</script>

</head>
<body>
<link rel = "stylesheet"  type="text/css" href="index.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	
 	</div>
		<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %}
				<p style="font-size: 200%; border-bottom:none;">
				 Welcome {{ username | capitalize }} <BR>
				 You have <i id="basketQuantity">0</i> items in your basket<BR>
				<a href='shoppingBagPage.php'>View Basket</a> or 
				<a href='paymentDetailsPage.php'>Checkout</a><BR>
				<a href='logout.php'>Log Out</a></p>
					{% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
						<span class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUserPage.php">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

<div id="content">
 
<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="search_Menu.php?department=All%20Cloths&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Woman%27s%20Cloths&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Mans%27s%20Cloths&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Dress&depart=womenswear&type=dress">Dress</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Skirt&depart=womenswear&type=skirt">Skirt</a></li>
				</ul>
            </li>
            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Shorts&depart=menswear&type=shorts">Shorts</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Kilt&depart=menswear&type=kilt">Kilt</a></li>
				<hr>
				<li><a href="search_Menu.php?department=T-Shirts&depart=menswear&type=tShirts">T-Shirts</a></li>
				</ul>
            </li>
            <li>
            <a href="#">STORE LOCATOR</a>
            </li>
            <li>
            <a href="#">ABOUT US</a>
            </li>
	</ul>
</div>

<div id="middle">
	<table style="margin-left: auto; margin-right: auto;">
	<tr>
	<td><img alt="" src="{{ item.image_link }}" width="400" /></td>
	<td style="text-align: left; vertical-align: text-top;">
	<div style="margin-left:100px;">
	<h1 style="font-weight: bold; text-align:center; margin-top:100px;" >
	Item description
</h1>
 <BR>

 {{ item.desc }}

 <BR><BR>
<FORM >
		<b>Size:</b><BR>
		<select name="selectSize" id="selectSize">
		<option value="{{ item.item_size }}">{{ item.item_size | capitalize }}</option>
		</select><BR><BR>
		<b>Colour:</b><BR>
		<select name="selectColour" id="selectColour" onchange="colourChanged();">
		<option value="{{ item.colour }}">{{ item.colour | capitalize }}</option>
		</select><BR><BR>
		<input type="button" id="addCartButton" value="Add to bag" onclick="addToBag();">
		
		</FORM>
		</div>
		</td>
		</tr>
</table>
</div>
</div>
<div id="footer">
	<br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
