<html>
<head>
<meta charset="UTF-8">
	<script type='text/javascript' language='Javascript'>

<!--
var requestObject = false;

var styleID = "styleID={{ style_ID | raw }}";
var quantity = 0;

function eliminateDuplicates(arr) {
	  var i,
	      len=arr.length,
	      out=[],
	      obj={};
	 
	  for (i=0;i<len;i++) {
	    obj[arr[i]]=0;
	  }
	  for (i in obj) {
	    out.push(i);
	  }
	  return out;
	}
	
		function funcReceiveData()
		{
			if (requestObject.readyState == 4)
			{
				if (requestObject.status == 200)
				{
					var status = requestObject.responseText;
					if(!((status == "An error occurred, please try again") || (status == "You're not logged in, please login.")))
					{
						var elItems = document.getElementById("basketQuantity");
						var numItems = parseInt(elItems.innerHTML);
						numItems +=  parseInt(quantity);
						elItems.innerHTML = numItems;
						//window.location.reload();							
					}
					alert(status);
				}
			}
		}

		if (window.XMLHttpRequest)
		{
			requestObject = new XMLHttpRequest();
		}
		else if (window.ActiveXObject)
		{
			requestObject = new ActiveXObject("Microsoft.XMLHTTP");
		}

		function addToBag()
		{
			var basket = document.getElementById("Vbasket");
			var check = document.getElementById("checOut");

			basket.style.display= "inline";
			check.style.display= "inline";
			
			if (requestObject) 
			{
				requestObject.open("POST", "addToBag.php", true);
				requestObject.setRequestHeader("Content-type",
						"application/x-www-form-urlencoded");
				var size = document.getElementById('selectSize').value;
				var colour = document.getElementById('selectColour').value;
				var q_tag = document.getElementById("quantity");
				var qindex = q_tag.selectedIndex;
				quantity = q_tag.options[qindex].value;
				var tobesent = "size=" + size + "&" + "colour=" + colour + "&styleID={{ style_ID | raw }}&name={{ item.name | raw }}&quantity="+quantity;
				requestObject.send(tobesent);
				requestObject.onreadystatechange = funcReceiveData;
			}
		}



	function getAllColourSizes()
	{
		var MyRequestObject = new XMLHttpRequest();

		if(MyRequestObject)
		{
			MyRequestObject.open("POST", "getColourSize.php", false);
			MyRequestObject.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
			MyRequestObject.send(styleID);
			var All = MyRequestObject.responseText;
			var strVec = All.split(";");
			var colours = strVec[0].split(",");
			var sizes = strVec[1].split(",");

			var colourClean = eliminateDuplicates(colours);
			var sizesClean = eliminateDuplicates(sizes);
			
			updateColour(colourClean);
			updateSizes(sizesClean);
		}
	}

	function updateColour(newColours)
	{
		colour_tag = document.getElementById("selectColour");
		
		colour_tag.options.length=0;

		for(var i = 0; i < newColours.length; i++)
			colour_tag.options[i]=new Option(newColours[i], newColours[i], false, false);
	}

	function updateSizes(newSizes)
	{
		size_tag = document.getElementById("selectSize");
		
		size_tag.options.length=0;

		for(var i = 0; i < newSizes.length; i++)
			size_tag.options[i]=new Option(newSizes[i], newSizes[i], false, false);
	}

	function sizeChanged() /* Update COLOUR!!! */
	{
		var MyRequestObject = new XMLHttpRequest();

		var size_tag = document.getElementById('selectSize');
		var index = size_tag.selectedIndex;
		
		if(MyRequestObject)
		{
			MyRequestObject.open("POST", "getColour.php", false);
			MyRequestObject.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
			MyRequestObject.send(styleID + "&size=" + size_tag.options[index].value);
			var All = MyRequestObject.responseText;
			var colours = All.split(",");

			var colourClean = eliminateDuplicates(colours);
			
			updateColour(colourClean);
		}
	}

	function colourChanged() /* Update SIZE!!! */
	{
		var MyRequestObject = new XMLHttpRequest();

		var colour_tag = document.getElementById('selectColour');
		var index = colour_tag.selectedIndex;

		if(MyRequestObject)
		{
			MyRequestObject.open("POST", "getSize.php", false);
			MyRequestObject.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
			MyRequestObject.send(styleID + "&colour=" + colour_tag.options[index].value);
			var All = MyRequestObject.responseText;
			var sizes = All.split(",");

			var sizesClean = eliminateDuplicates(sizes);
			
			updateSizes(sizesClean);
		}
	}

	function changePrice()
	{
		//return;
		var MyRequestObject = new XMLHttpRequest();

		var colour_tag = document.getElementById('selectColour');
		var indexc = colour_tag.selectedIndex;

		var size_tag = document.getElementById('selectSize');
		var indexs = size_tag.selectedIndex;

		var price_tag = document.getElementById("price");
		if(MyRequestObject)
		{
			MyRequestObject.open("POST", "getPrice.php", false);
			MyRequestObject.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
			MyRequestObject.send(styleID + "&colour=" + colour_tag.options[indexc].value + "&size=" + size_tag.options[indexs].value);
			var price = MyRequestObject.responseText;
			price_tag.innerHTML = "£" + price;
		}
			
	}


window.onload = getAllColourSizes;
</script>

</head>
<body>
<link rel = "stylesheet"  type="text/css" href="index.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	
 	</div>
		<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %}
				<p style="font-size: 150%; border-bottom:none;">
				 Welcome {{ username | capitalize }} <BR>
				 You have <i id="basketQuantity">{{ num_items | raw }}</i> items in your basket<BR>
			
				                {% if num_items > 0 %}
                                <a id="Vbasket" href='shoppingBagPage.php'>View Basket</a><BR>
                                <a id="checOut" href='paymentDetailsPage.php'>Checkout</a><BR>
                                {% else %}
                                <a id="Vbasket" href='shoppingBagPage.php' style="display: none;" >View Basket</a><BR>
                                <a id="checOut" href='paymentDetailsPage.php' style="display: none;" >Checkout</a><BR>
                                {% endif %}

				<a href='logout.php'>Log Out</a></p>
					{% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span style="color:#20B2AA" class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
					<span style="color:#20B2AA" class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUserPage.php">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

<div id="content">
 
<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="search_Menu.php?department=All%20Cloths&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Woman%27s%20Cloths&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Mans%27s%20Cloths&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Dress&depart=womenswear&type=dress">Dress</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Skirt&depart=womenswear&type=skirt">Skirt</a></li>
				</ul>
            </li>
            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Shorts&depart=menswear&type=shorts">Shorts</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Kilt&depart=menswear&type=kilt">Kilt</a></li>
				<hr>
				<li><a href="search_Menu.php?department=T-Shirts&depart=menswear&type=tShirts">T-Shirts</a></li>
				</ul>
            </li>
            <li>
            <a href="#">STORE LOCATOR</a>
            </li>
            <li>
            <a href="#">ABOUT US</a>
            </li>
	</ul>
</div>

<div id="middle">
	<table style="margin-left: auto; margin-right: auto;">
	<tr>
	<td><img alt="" src="{{ item[0].image_link }}" width="400" style="margin-top: 40px;" /></td>
	<td style="text-align: left; vertical-align: text-top;">
	<div style="margin-left:100px;">
	<h1 style="font-weight: bold; text-align:center; margin-top:100px;" >
	{{ item[0].name | raw }}
</h1>

 <BR>

 {{ item[0].desc }}

 <BR><BR>
 <b id="price">£{{ item[0].price }}</b><BR><BR>
<FORM >
		<b>Size:</b><BR>
		<select name="selectSize" id="selectSize" onchange="sizeChanged();changePrice();">
		<option value="{{ item[0].item_size }}">{{ item.item_size | capitalize }}</option>
		</select><BR><BR>
		<b>Colour:</b><BR>
		<select name="selectColour" id="selectColour" onchange="colourChanged();changePrice();">
		<option value="{{ item[0].colour }}">{{ item[0].colour | capitalize }}</option>
		</select><BR><BR>
		<b>Quantity:</b><BR>
				<select name="quantity" id="quantity">
			{% for i in 1..10 %}
				<option value="{{ i }}">{{ i }}</option>
			{% endfor %}
		</select><BR><BR>
		<input type="button" id="addButton" value="Add to bag" onclick="addToBag();">
		</FORM>
		</div>
		</td>
		</tr>
</table>
</div>
</div>
<div id="footer">
	<br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
