<html>
<head>
<script type='text/javascript' language='Javascript'>
<!--

var images = Array();

var i = 0;

{% for image in slideShowImages %}
	images[i] = new Image();
	images[i++].src = "{{ image }}";
{% endfor %}

function countImgs(max)
{
    // Check to see if the counter has been initialized
    if ( typeof countImgs.i == 'undefined' )
    {
        // It has not... perform the initilization
        countImgs.i = 0;
    }
    countImgs.i = (countImgs.i + 1)%max;
    return countImgs.i;
}

function changeImage()
{
	document['imgRoll'].src = images[countImgs({{ imgCount }})].src;
}

var mytimer = setInterval(function(){changeImage()}, 3000);

//-->
</script>
</head>
<body>

<a id="tooCool" href="http://www.w3junkies.com/toocool/">Too Cool for Internet Explorer</a>

<link rel = "stylesheet"  type="text/css" href="index.css">

<div id = "header">
 <div id ="headerlogo"> <img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo"> </div>
 <div id="login"> 
 <div id="stylized" class="myform">
<form id="form" name="form" method="post" action="index.html">

<label>Username
<span class="small">Type your username</span>
</label>
<input type="text" name="usr" id="usr" />

<label>Password
<span class="small">Min. size 6 chars</span>
</label>
<input type="password" name="password" id="password" />

<button type="submit">Login</button> </br></br>
<center><a id="signup" style="font-size:14px;" href="#">Don't have an account? Sign up here!</a></center>
<div class="spacer"></div>

</form>
</div>
 </div>
 </div>

<div id="content">
 
<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="#">View All</a></li>
				<hr>
				<li><a href="#">Women</a></li>
				<hr>
				<li><a href="#">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="womens.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="womens.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="womens.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				</ul>
            </li>


            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="womens.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="womens.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="womens.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				</ul>
            </li>
            
            <li>
            <a href="#">GIRLS</a>
                <ul>  
				<li><a href="#">Coats & Jackets</a></li>
				<hr>
				<li><a href="#">Jeans</a></li>
				<hr>
				<li><a href="#">Knitwear</a></li>
				
				</ul> 
            </li>
            <li>
            <a href="#">BOYS</a>
                <ul>  
				<li><a href="#">Coats & Jackets</a></li>
				<hr>
				<li><a href="#">Jeans</a></li>
				<hr>
				<li><a href="#">Knitwear</a></li>
				
				</ul> 
            </li>
                        <li>
            <a href="#">BABIES</a>
  
            </li>
            
            <li>
            <a href="#">SALES</a>
				<ul>  
				<li><a href="#">Women</a></li>
				<hr>
				<li><a href="#">Men</a></li>
				
				</ul> 
            </li>
            <li>
            <a href="#">STORE LOCATOR</a>
            </li>
			
            
			
            <li>
            <a href="#">ABOUT US</a>
            </li>
	</ul>

</div>
<div id="middle">

	<div class="image1">
  <img alt="" id="rollImage" src="slideshowpictures/mcoat1.jpg" name="imgRoll"/>
  <div class="textimg1">
    <a href="#" style="margin-left: 4px;">SPRING COLLECTION 2013</a>
    <a href="#" style="float:right; font-size: 35px;margin-right: 3px;">Jackets from &pound;20</a>
  </div>
</div>

</div>
<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
