<html>
<meta charset="UTF-8">
<body>
  
<link rel = "stylesheet"  type="text/css" href="payment.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	
 	</div>
		<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %}
				<p style="font-size: 200%; border-bottom:none;">
				 Welcome {{ username | capitalize }} <BR>
				 You have <i id="basketQuantity">{{ num_items | raw }}</i> items in your basket<BR>

				                                {% if num_items > 0 %}
                                <a href='shoppingBagPage.php'>View Basket</a> or
                                <a href='paymentDetailsPage.php'>Checkout</a><BR>
                                {% endif %}

				<a href='logout.php'>Log Out</a></p>
					{% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span style="color:#FF1493" class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
					<span style="color:#FF1493" class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUserPage.php">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

<div id="content">
 
<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="search_Menu.php?department=All%20Cloths&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Woman%27s%20Cloths&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Mans%27s%20Cloths&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Dress&depart=womenswear&type=dress">Dress</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Skirt&depart=womenswear&type=skirt">Skirt</a></li>
				</ul>
            </li>
            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Shorts&depart=menswear&type=shorts">Shorts</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Kilt&depart=menswear&type=kilt">Kilt</a></li>
				<hr>
				<li><a href="search_Menu.php?department=T-Shirts&depart=menswear&type=tShirts">T-Shirts</a></li>
				</ul>
            </li>
            <li>
            <a href="#">STORE LOCATOR</a>
            </li>
            <li>
            <a href="#">ABOUT US</a>
            </li>
	</ul>
</div>


<div id="middle">	
	
		<fieldset>
	<form method="POST" action="paymentDetails.php">
		<p style="font-size: 23px; float: left; font-weight: bold; margin-left: 20%;">Payment Details</p><button id="editBtn" type="button">EDIT YOUR SHOPPING BAG</button>
		<br><br><br><br>
					<div id="paymentForm">
		<p> Total Amount </p><br><br>
		<p>Select your card </p>
		<select name="cardType">
			<option value="mastercard">MasterCard</option>
			<option value="maestro">Maestro</option>
			<option value="visa">Visa</option>
			<option value="visaelectron">Visa Electron</option>
			<option value="americanexpress">American Express</option>
		</select>
		<br><br>
		<p>Name </p> <input type="text" name="name" size="25"><br>
		<p>Card number </p><input type="text" name="cardnumber" size="25"><br>
		<p>Security Code </p><input type="text" name="securitycode" size="25"><br>
		<p>Expiry Date</p>
		<select name="month">
		<option value="1">01</option>
		<option value="2">02</option>
		<option value="3">03</option>
		<option value="4">04</option>
		<option value="5">05</option>
		<option value="6">06</option>
		<option value="7">07</option>
		<option value="8">08</option>
		<option value="9">09</option>
		<option value="10">10</option>
		<option value="11">11</option>
		<option value="12">12</option>	
		</select>
		<select name="year">
		<option value="2013">2013</option>
		<option value="2014">2014</option>
		<option value="2015">2015</option>
		<option value="2016">2016</option>
		<option value="2017">2017</option>
		<option value="2018">2018</option>
		<option value="2019">2019</option>
		<option value="2020">2020</option>
		</select>
		<br><br>
		<!--  <input type="checkbox" name="rememberDetails" style="display:inline;"><p> I would like to remember the payment details above</p><br><br>
		<input style="width:150px; background: -webkit-gradient(linear, left top, left 25, from(#FFFFFF), color-stop(4%, #EEEEEE), to(#E0EEEE));" type="submit" value="Confirm"/>-->
			</div>
			<br><br>
				<p style="font-size: 23px; font-weight: bold; margin-left: 20%;">Delivery Address</p><br>
			<p id="txt"style="margin-left:20%;">Would you like to send it to your address? </p><br><br>
			<script language="javascript"> 
				function toggle() {
					var ele1 = document.getElementById("newAddr");
					var ele2 = document.getElementById("addr");
					var ele3 = document.getElementById("txt");
					var btn = document.getElementById("changeAddr");
					var hfield = document.getElementById("userAddress");
					hfield.value = "0";
					
					if(ele1.style.display == "block") {
						ele1.style.display = "none";
						ele2.style.display = "block";		
					} else {
						ele1.style.display = "block";
						ele2.style.display = "none";
						ele3.style.display = "none";
						btn.style.display = "none";
					}
				} 
			</script>
			<div id="addr" style="margin-left:26%; font-size:14px;">
		
				{{ address1 }} <br>
				{{ address2 }}<BR>
				{{ city }}<br>
				{{ postcode }}<br>
			
			</div>
			<br><br>
			<input type="button" id="changeAddr" onClick="javascript:toggle();" value="CHANGE ADDRESS"><br>
			<div id="newAddr" style="display: none;">
				<p>Address Line 1</p> <input type="text" name="address1" size="25" value="{{ address1 }}"><br>
				<p>Address Line 2 </p><input type="text" name="address2" size="25" value="{{ address2 }}"><br>
				<p>City</p><input type="text" name="city" size="25" value="{{ city }}"><br>
				<p>Postcode </p><input type="text" name="postcode" size="25" value="{{ postcode }}"><br>
				<input type="hidden" name="userAddress" value="1" id="userAddress">

			</div>
				<br><br>

			               <input style="width: 30%; height: 30px; margin-left: 25%; background-color: blueviolet;background: -webkit-gradient(linear, left top, left 25, from(#FFFFFF), color-stop(4%, #EEEEEE), to(#E0EE EE)); border-radius: 4; -moz-border-radius: 4; -webkit-border-radius: 4; background-color: #CDCDB4;" type="submit" value="Confirm Payment and Address"/>
			
			</form>
				</fieldset>

	
</div>

</div>
<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
