<html>
<head>
<meta charset="UTF-8">

</head>
<body>
<a id="tooCool" href="http://www.w3junkies.com/toocool/">Too Cool for Internet Explorer</a>
<link rel = "stylesheet"  type="text/css" href="index.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	
 	</div>
		<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %}
				<p style="font-size: 200%; border-bottom:none;">
				 Welcome {{ username | capitalize }} <BR>
				 You have <i id="basketQuantity">0</i> items in your basket<BR>
				<a href='shoppingBagPage.php'>View Basket</a> or 
				<a href='paymentDetailsPage.php'>Checkout</a><BR>
				<a href='logout.php'>Log Out</a></p>
					{% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
						<span class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUserPage.php">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

<div id="content">
 
<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="search_Menu.php?department=All%20Cloths&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Woman%27s%20Cloths&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Mans%27s%20Cloths&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Dress&depart=womenswear&type=dress">Dress</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Skirt&depart=womenswear&type=skirt">Skirt</a></li>
				</ul>
            </li>
            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Shorts&depart=menswear&type=shorts">Shorts</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Kilt&depart=menswear&type=kilt">Kilt</a></li>
				<hr>
				<li><a href="search_Menu.php?department=T-Shirts&depart=menswear&type=tShirts">T-Shirts</a></li>
				</ul>
            </li>
            <li>
            <a href="#">STORE LOCATOR</a>
            </li>
            <li>
            <a href="#">ABOUT US</a>
            </li>
	</ul>
</div>

	<h1 style="font-weight: bold; text-align:center" >
	{{ department | raw }}
	</h1>

<!--
<div class = "sortDropdown">
<select>
  <option value="Favourites">Favourites</option>
  <option value="Most Popular">Most Popular</option>
  <option value="Price Low-High">Price Low-High</option>
  <option value="Price High-Low">Price High-Low</option>
</select>
</div>
-->
   <table style="margin: auto;">
		<tr valign="top">
			<td>
			<div>
			<form id="frmsizes" method="POST" name="frmsizes" action="searchCloths.php">
						<table>
							<tr>
								<td><p class="tag">COLOUR</p></td>
							</tr>
							<tr>
								<td>
									<p>
										<input type="checkbox" id="ckblue" class="regular-checkbox" name="colour_list[]" value="blue" {% if blue is defined %} checked {% endif %} /><label for="ckblue"></label>
										Blue
									</p>
									<p>
										<input type="checkbox" id="ckblack" class="regular-checkbox" name="colour_list[]" value="black" {% if black is defined %} checked {% endif %} /><label for="ckblack"></label>
										Black
									</p>
									<p>
										<input type="checkbox" id="ckred" class="regular-checkbox" name="colour_list[]" value="red" {% if red is defined %} checked {% endif %} /><label for="ckred"></label>
										Red
									</p>
									<p>
										<input type="checkbox" id="ckwhite" class="regular-checkbox" name="colour_list[]" value="white" {% if white is defined %} checked {% endif %} /><label for="ckwhite"></label>
										White
									</p>
								</td>
								<td>
									<p>
										<input type="checkbox" id="ckyellow" class="regular-checkbox" name="colour_list[]" value="yellow" {% if yellow is defined %} checked {% endif %} /><label for="ckyellow"></label>
										Yellow
									</p>
									<p>
										<input type="checkbox" id="ckpink" class="regular-checkbox" name="colour_list[]" value="pink" {% if pink is defined %} checked {% endif %} /><label for="ckpink"></label>
										Pink
									</p>
									<p>
										<input type="checkbox" id="ckgray" class="regular-checkbox" name="colour_list[]" value="gray" {% if gray is defined %} checked {% endif %} /><label for="ckgray"></label>
										Gray
									</p>
									<p>
										<input type="checkbox" id="ckgreen" class="regular-checkbox" name="colour_list[]" value="green" {% if green is defined %} checked {% endif %} /><label for="ckgreen"></label>
										Green
									</p>
								</td>
							</tr>

							<tr>
								<td><p class="tag">SIZE</p></td>
							</tr>
							<tr>
								<td>
									<p>
										<input type="checkbox" id="ckxs" class="regular-checkbox" value="xsamll" name="size_list[]" {% if xsamll is defined %} checked {% endif %} /><label for="ckxs"></label> X-Small
									</p>
									<p>
										<input type="checkbox" id="cks" class="regular-checkbox" value="small" name="size_list[]" {% if small is defined %} checked {% endif %} /><label for="cks"></label> Small
									</p>
									<p>
										<input type="checkbox" id="ckm" class="regular-checkbox" value="medium" name="size_list[]" {% if medium is defined %} checked {% endif %} /><label for="ckm"></label> Medium
									</p>
									<p>
										<input type="checkbox" id="ckl" class="regular-checkbox" value="large" name="size_list[]" {% if large is defined %} checked {% endif %} /><label for="ckl"></label> Large
									</p>
								</td>
								<td>
									<p>
										<input type="checkbox" id="ckxl" class="regular-checkbox" value="xlarge" name="size_list[]" {% if xlarge is defined %} checked {% endif %} /><label for="ckxl"></label> X-Large
									</p>
									<p>
										<input type="checkbox" id="ckxxl" class="regular-checkbox" value="xxlarge" name="size_list[]" {% if xxlarge is defined %} checked {% endif %} /><label for="ckxxl"></label> XX-Large
									</p>
									<p>
										<input type="checkbox" id="ckxxxl" class="regular-checkbox" value="xxxlarge" name="size_list[]" {% if xxxlarge is defined %} checked {% endif %} /><label for="ckxxxl"></label> XXX-Large
									</p>
								</td>
							</tr>
							<tr><td><input type="submit" value="Update"></td></tr>
						</table>
						<input type="hidden" name="department" id="department" value="{{ department | raw }}" />
						<input type="hidden" name="dep_query" id="dep_query" value="{{ dep_query | raw }}" />
						<input type="hidden" name="type_query" id="type_query" value="{{ type_query | raw }}" />
						</form>
					</div>
			</td>
				
			<td>
			<table>
				<tr>
					{% for image in womensCloths %}
					{% if loop.first == false %}
						{% if (loop.index0 % 4) == 0 %}
							</tr>
							<tr>
						{% endif %}
					{% endif %}
					<td>
 					<div class = "allIamges">
						<a href="#"  ><img alt="{{ image.alt | raw }}" id="img{{ image.id }}" src="{{ image.src }}" width="144" high="216" /></a>
						<div id="links">
							<a href="#"  >{{ image.name | raw }}<BR>Colour: <b>{{ image.colour | capitalize }}</b><BR></a>
							<a href="#" ><strong>£{{ image.price }}</strong></a>
						</div>
					</div>
					</td>
					{% if loop.last %}
						{% if (loop.index % 4) != 0 %}
							</tr>
						{% endif %}
					{% endif %}
					{% endfor %}
				</table>
			</td>
		</tr>
	</table>

<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
