<html>
<meta charset="UTF-8">
<script>
var requestObject = false;
function removeFromBag(id, rid)
		{
		requestObject = new XMLHttpRequest();
			if (requestObject) 
			{
				requestObject.open("POST", "removeBag.php", false);
				requestObject.setRequestHeader("Content-type",
						"application/x-www-form-urlencoded");
				
				var tobesent = "itemID=" + id;
				requestObject.send(tobesent);
				var response = requestObject.responseText;
			
			var table = document.getElementById("ItemsTable");
			var row=document.getElementById(rid);
			var qt = row.cells[3].getElementsByTagName("select")[0].value;
			
			
			table.deleteRow(row.rowIndex);
			var elItems = document.getElementById("basketQuantity");
			var numItems = elItems.innerHTML;
			numItems = numItems - qt;
			elItems.innerHTML = numItems;

				if (numItems == 0) {
					window.location = 'index.php';
				}
			}
		}

		function changeQuantity(id, rid)
		{
			requestObject = new XMLHttpRequest();
			//var table = document.getElementById("ItemsTable");
			var row=document.getElementById(rid);
			var qt = row.cells[3].getElementsByTagName("select")[0].value;
			var max_items = row.cells[3].getElementsByTagName("select")[0].options.length;
			
			if (requestObject) 
			{
				requestObject.open("POST", "updateQuantityBag.php", false);
				requestObject.setRequestHeader("Content-type",
						"application/x-www-form-urlencoded");
				
				var tobesent = "itemID=" + id + "&quantity=" + qt;
				requestObject.send(tobesent);
				
				var price = requestObject.responseText;
				var elItems = document.getElementById("basketQuantity");
				var numItems = elItems.innerHTML;
				var removed = (max_items - qt);
				numItems = numItems - removed;
				elItems.innerHTML = numItems;

				row.cells[3].getElementsByTagName("select")[0].options.length = 0;
				for(var i=0; i < qt; i++)
				{
					if(i == (qt - 1))
						row.cells[3].getElementsByTagName("select")[0].options[i] = new Option(i + 1, i + 1, false, true);
					else
						row.cells[3].getElementsByTagName("select")[0].options[i] = new Option(i + 1, i + 1, false, false);
				}

				row.cells[5].innerHTML = "<b>£" + (price*qt) + "</b>";
			}
			
		}
</script>
<body>
  
<link rel = "stylesheet"  type="text/css" href="shoppingBag.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	
 	</div>
		<div id="login">
			<div id="stylized" class="myform">
				{% if logged == 1 %}
				<p style="font-size: 150%; border-bottom:none;">
				 Welcome {{ username | capitalize }} <BR>
				 You have <i id="basketQuantity">{{ num_items | raw }}</i> items in your basket<BR>

				                {% if num_items > 0 %}
                                <a id="Vbasket" href='shoppingBagPage.php'>View Basket</a><BR>
                                <a id="checOut" href='paymentDetailsPage.php'>Checkout</a><BR>
                                {% else %}
                                <a id="Vbasket" href='shoppingBagPage.php' style="display: none;" >View Basket</a><BR>
                                <a id="checOut" href='paymentDetailsPage.php' style="display: none;" >Checkout</a><BR>
                                {% endif %}

				<a href='logout.php'>Log Out</a></p>
					{% else %}
				<form id="form" name="form" method="POST" action="login.php">

					<label>Username <span style="color:#20B2AA" class="small">Type your username</span>
					</label> <input type="text" name="usr" id="usr" /> <label>Password
						<span style="color:#20B2AA" class="small">Min. size 6 chars</span>
					</label> <input type="password" name="password" id="password" />

					<button type="submit">Login</button>
					</br> </br>
					<center>
						<a id="signup"
							style="font-size: 14px;" href="addUserPage.php">Don't have an
							account? Sign up here!</a>
					</center>
					<div class="spacer"></div>

				</form>
				{% endif %}
			</div>
		</div>
 </div>

<div id="content">
 
<div id="nav">
	 <ul>		
             <li id="newin">
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="search_Menu.php?department=All%20Clothes&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Women%27s%20Clothes&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="search_Menu.php?department=All%20Mens%27s%20Clothes&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Dress&depart=womenswear&type=dress">Dress</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Skirt&depart=womenswear&type=skirt">Skirt</a></li>
				</ul>
            </li>
            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="search_Menu.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Shorts&depart=menswear&type=shorts">Shorts</a></li>
				<hr>
				<li><a href="search_Menu.php?department=Kilt&depart=menswear&type=kilt">Kilt</a></li>
				<hr>
				<li><a href="search_Menu.php?department=T-Shirts&depart=menswear&type=tShirts">T-Shirts</a></li>
				</ul>
            </li>
            <li>
            <a href="storeLocatorPage.php">STORE LOCATOR</a>
            </li>
            <li>
            <a href="aboutUsPage.php">ABOUT US</a>
            </li>
	</ul>
</div>

<div id="middle">
	<img id="shoppingbag" style="padding:10px;" src="shoppingbag.jpg"> <input type="button" id="checkoutBtn" type="button" value="CHECKOUT" onclick="window.location.href='paymentDetailsPage.php'">
	<h2>YOUR SHOPPING BAG</h2>
	<table id="ItemsTable">
	<tr id="ItemRow">
		<th style="width:35%;">Items</th>
		<th style="width:12%;">Size</th>
		<th style="width:12%;">Colour</th>
		<th style="width:12%;">Quantity</th>
		<th style="width:15%;">Delivery day</th>
		<th style="width:21%;">Total</th>
	</tr>
	{% for item in items %}
	<tr id ="row{{ item.itemID }}" style="text-align:center;">
	<td>
	<img alt="{{ item.desc }}" src="{{ item.image_link }}" width="144" high="216" /><BR>
	<b>{{ item.name | capitalize }}</b><BR>
	<input type="button" id="remove" value="Remove from bag" onclick="removeFromBag({{ item.itemID }}, 'row{{ item.itemID }}');">
	</td>
	<td>{{ item.size | capitalize }}</td>
	<td>{{ item.colour | capitalize }}</td>
	<td>
		<select name="quantity{{ item.itemID | raw }}" onchange="changeQuantity({{ item.itemID }}, 'row{{ item.itemID }}');">
		{% for i in 1..item.quantity %}
			
			{% if loop.last %}
				<option value="{{ i }}" selected >{{ i }}</option>
			{% else %}
				<option value="{{ i }}" >{{ i }}</option>
			{% endif %}
		{% endfor %}
		</select>
		</td>
	<td>{% if item.aval == 1 %} Tomorrow {% else %} Next week {% endif %} </td>
	<td><b>£{{ item.price }}</b></td>
	</tr>
	{% endfor %}

	</table>
	
</div>

</div>
<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
