<html>
<head>
<meta charset="UTF-8">
</head>
<body>
<a id="tooCool" href="http://www.w3junkies.com/toocool/">Too Cool for Internet Explorer</a>
<link rel = "stylesheet"  type="text/css" href="index.css">

<div id = "header">
 <div id ="headerlogo">
 	<a href="index.php">
 		<img style="margin-left:100px; margin-top:0px;" id ="logo" src= "logo1.png" alt="logo">
 	</a>
 	</div>
      <a href="#" >
	   <div class="button">
              <span class="ButtonText ">Checkout</span>
		</div>
      </a>
 </div>

<div id="content">
 
<div id="nav">
	 <ul>		
             <li>
            <a href="#">NEW IN</a>
			<ul>  
				<li><a href="womens.php?department=All%20Cloths&depart=all&type=any">View All</a></li>
				<hr>
				<li><a href="womens.php?department=All%20Woman%27s%20Cloths&depart=womenswear&type=any">Women</a></li>
				<hr>
				<li><a href="womens.php?department=All%20Mans%27s%20Cloths&depart=menswear&type=any">Men</a></li>
				
				</ul> 
            </li>
			
			 <li >
            <a href="#">WOMEN</a>
                <ul> 
				<li><a href="womens.php?department=Coats%20%26%20Jackets&depart=womenswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="womens.php?department=Jeans&depart=womenswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="womens.php?department=Knitwear&depart=womenswear&type=knitwear">Knitwear</a></li>
				</ul>
            </li>


            <li>
            <a href="#">MEN</a>
                <ul> 
				<li><a href="womens.php?department=Coats%20%26%20Jackets&depart=menswear&type=coats"">Coats & Jackets</a></li>
				<hr>
				<li><a href="womens.php?department=Jeans&depart=menswear&type=jeans">Jeans</a></li>
				<hr>
				<li><a href="womens.php?department=Knitwear&depart=menswear&type=knitwear">Knitwear</a></li>
				</ul>
            </li>
            
            <li>
            <a href="#">GIRLS</a>
                <ul>  
				<li><a href="#">Coats & Jackets</a></li>
				<hr>
				<li><a href="#">Jeans</a></li>
				<hr>
				<li><a href="#">Knitwear</a></li>
				
				</ul> 
            </li>
            <li>
            <a href="#">BOYS</a>
                <ul>  
				<li><a href="#">Coats & Jackets</a></li>
				<hr>
				<li><a href="#">Jeans</a></li>
				<hr>
				<li><a href="#">Knitwear</a></li>
				
				</ul> 
            </li>
                        <li>
            <a href="#">BABIES</a>
  
            </li>
            
            <li>
            <a href="#">SALES</a>
				<ul>  
				<li><a href="#">Women</a></li>
				<hr>
				<li><a href="#">Men</a></li>
				
				</ul> 
            </li>
            <li>
            <a href="#">STORE LOCATOR</a>
            </li>
			
            
			
            <li>
            <a href="#">ABOUT US</a>
            </li>
	</ul>

</div>

	<h1 style="font-weight: bold; text-align:center" >
	{{ department | raw }}
	</h1>

<!--
<div class = "sortDropdown">
<select>
  <option value="Favourites">Favourites</option>
  <option value="Most Popular">Most Popular</option>
  <option value="Price Low-High">Price Low-High</option>
  <option value="Price High-Low">Price High-Low</option>
</select>
</div>
-->
   <table style="margin: auto;">
		<tr valign="top">
			<td>
			<div>
						<table>
							<tr>
								<td><p class="tag">COLOUR</p></td>
							</tr>
							<tr>
								<td>
									<p>
										<input type="checkbox" id="checkbox-1-1"
											class="regular-checkbox" /><label for="checkbox-1-1"></label>
										Blue
									</p>
									<p>
										<input type="checkbox" id="checkbox-1-2"
											class="regular-checkbox" /><label for="checkbox-1-2"></label>
										Black
									</p>
									<p>
										<input type="checkbox" id="checkbox-1-3"
											class="regular-checkbox" /><label for="checkbox-1-3"></label>
										Red
									</p>
									<p>
										<input type="checkbox" id="checkbox-1-4"
											class="regular-checkbox" /><label for="checkbox-1-4"></label>
										White
									</p>
								</td>
								<td>
									<p>
										<input type="checkbox" id="checkbox-2-1"
											class="regular-checkbox" /><label for="checkbox-2-1"></label>
										Yellow
									</p>
									<p>
										<input type="checkbox" id="checkbox-2-2"
											class="regular-checkbox" /><label for="checkbox-2-2"></label>
										Pink
									</p>
									<p>
										<input type="checkbox" id="checkbox-2-3"
											class="regular-checkbox" /><label for="checkbox-2-3"></label>
										Gray
									</p>
									<p>
										<input type="checkbox" id="checkbox-2-4"
											class="regular-checkbox" /><label for="checkbox-2-4"></label>
										Green
									</p>
								</td>
							</tr>

							<tr>
								<td><p class="tag">SIZE</p></td>
							</tr>
							<tr>
								<td>
									<p>
										<input type="checkbox" id="checkbox-3-1"
											class="regular-checkbox" /><label for="checkbox-3-1"></label>
										X-Small
									</p>
									<p>
										<input type="checkbox" id="checkbox-3-2"
											class="regular-checkbox" /><label for="checkbox-3-2"></label>
										Small
									</p>
									<p>
										<input type="checkbox" id="checkbox-3-3"
											class="regular-checkbox" /><label for="checkbox-3-3"></label>
										Medium
									</p>
									<p>
										<input type="checkbox" id="checkbox-3-4"
											class="regular-checkbox" /><label for="checkbox-3-4"></label>
										Large
									</p>
								</td>
								<td>
									<p>
										<input type="checkbox" id="checkbox-2-1"
											class="regular-checkbox" /><label for="checkbox-2-1"></label>
										X-Large
									</p>
									<p>
										<input type="checkbox" id="checkbox-2-2"
											class="regular-checkbox" /><label for="checkbox-2-2"></label>
										XX-Large
									</p>
									<p>
										<input type="checkbox" id="checkbox-2-3"
											class="regular-checkbox" /><label for="checkbox-2-3"></label>
										XXX-Large
									</p>

								</td>
							</tr>
						</table>
					</div>
			</td>
				
			<td>
			<table>
				<tr>
					{% for image in womensCloths %}
					{% if loop.first == false %}
						{% if (loop.index0 % 4) == 0 %}
							</tr>
							<tr>
						{% endif %}
					{% endif %}
					<td>
 					<div class = "allIamges">
						<a href="#"  ><img alt="{{ image.alt | raw }}" id="img{{ image.id }}" src="{{ image.src }}"  /></a>
						<div id="links">
							<a href="#"  >{{ image.desc | raw }}</a>
							<a href="#" ><strong >£{{ image.price }}</strong></a>
						</div>
					</div>
					</td>
					{% if loop.last %}
						{% if (loop.index % 4) != 0 %}
							</tr>
						{% endif %}
					{% endif %}
					{% endfor %}
				</table>
			</td>
		</tr>
	</table>




<div id="footer">
	</br>
<p style="text-align:center;"> &copy; 2013 Hamptons Store Ltd. All Rights Reserved.</p>

<ul id="footerList">
	<h3>Help</h3>
<li> <a href="#"> Frequently Asked Questions</a></li>
<li> <a href="#">Size Guides</a> </li>
<li><a href="#">Delivery Information</a></li>
<li> <a href="#">Customer Services</a></li>
<li> <a href="#">Site Map</a></li>
</ul>

<ul>
	<br><br>
<li><img style="width:25px; margin-left:50px;" id ="flogo" src= "f_logo.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.facebook.com/HamptonsStoreUK</a></li>
<br>
<li><img style="width:35px; margin-left:45px;" id ="tlogo" src= "twitter2.png" alt="logo"><a style="font-size:12px; margin-left:8px" href="#"> www.twitter.com/HamptonsStoreUK</a></li>
</ul>
</div>


</body>
</html>
